# Generated by Django 5.2.4 on 2025-08-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_pet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('author', models.CharField(max_length=20)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
