# Generated by Django 5.2.4 on 2025-08-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='published_date',
            field=models.DateField(),
        ),
    ]
